test:
	g++ src/test_blas.cpp src/timer.cpp -llapack -lblas -o bin/teste

test_nv2:
	g++ src/parallel_blas2.cpp src/timer.cpp -llapack -lopenblas -o bin/teste_blas2

test_nv3:
	g++ src/parallel_blas3.cpp src/timer.cpp -llapack -lopenblas -o bin/teste_blas3

test_plasma:

test_cusolver:
